networks:
 nrc-internal:
  internal: true
 public:
  driver: bridge

volumes:
 nrc-data:
  external: true

services:
 backend:
  build: ./backend
  volumes:
  - nrc-data:/home/AppData
  environment:
  - SERVER_HOSTNAME=backend
  - SERVER_PORT=8000
  - MONGODB_URI=mongodb://<username>:<password>@<dbIpAddr>:27017
  - FILE_STORAGE_PATH=/home/AppData
  - VUE_URI=http://<hostIpAddr>:80
  - SMTP_USER=<user email>
  - SMTP_PASS=<email pass>
  restart: on-failure
  networks:
  - nrc-internal
  - public

 frontend:
  build: 
   context: ./frontend
  ports:
  - "80:80"
  depends_on:
  - backend
  networks:
  - nrc-internal
  - public